/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 09fd272be10970e01c8990fa5cf3029f)
interface __BaseEnv_Env {
	GITHUB_REPOSITORY: string;
	GITHUB_WORKFLOW: string;
	GITHUB_REF: string;
	ENABLED: string;
	DRY_RUN: string;
	SCHEDULE_ENABLED: string;
	GITHUB_SCHEDULE_WORKFLOW: string;
	GITHUB_TOKEN: string;
	SCHEDULER: DurableObjectNamespace<import("./src/index").CinemaScheduler>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "CinemaScheduler";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_REPOSITORY" | "GITHUB_WORKFLOW" | "GITHUB_REF" | "ENABLED" | "DRY_RUN" | "SCHEDULE_ENABLED" | "GITHUB_SCHEDULE_WORKFLOW" | "GITHUB_TOKEN">> {}
}
