/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 08f7dd57edf19125289e3f08a994e43d)
interface __BaseEnv_Env {
	ENABLED: string;
	SCHEDULE_ENABLED: string;
	SEATS_ENABLED: string;
	AWS_REGION: string;
	GITHUB_SCHEDULE_ENABLED: string;
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	GITHUB_TOKEN: string;
	SCHEDULER: DurableObjectNamespace<import("./src/index").CinemaScheduler>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "CinemaScheduler";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENABLED" | "SCHEDULE_ENABLED" | "SEATS_ENABLED" | "AWS_REGION" | "GITHUB_SCHEDULE_ENABLED" | "AWS_ACCESS_KEY_ID" | "AWS_SECRET_ACCESS_KEY" | "GITHUB_TOKEN">> {}
}
