/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: 7d8032e2c6bd4ad2c787793a139a50f7)
interface __BaseEnv_Env {
	ENABLED: string;
	SCHEDULE_ENABLED: string;
	SEATS_ENABLED: string;
	AWS_REGION: string;
	GITHUB_SCHEDULE_ENABLED: string;
	GITHUB_SEATS01_ENABLED: string;
	GITHUB_SEATS02_ENABLED: string;
	GITHUB_SEATS03_ENABLED: string;
	GITHUB_SEATS04_ENABLED: string;
	GITHUB_SEATS05_ENABLED: string;
	GITHUB_SEATS06_ENABLED: string;
	GITHUB_SEATS07_ENABLED: string;
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	GITHUB_TOKEN: string;
	SCHEDULER: DurableObjectNamespace<import("./src/index").CinemaScheduler>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "CinemaScheduler";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENABLED" | "SCHEDULE_ENABLED" | "SEATS_ENABLED" | "AWS_REGION" | "GITHUB_SCHEDULE_ENABLED" | "GITHUB_SEATS01_ENABLED" | "GITHUB_SEATS02_ENABLED" | "GITHUB_SEATS03_ENABLED" | "GITHUB_SEATS04_ENABLED" | "GITHUB_SEATS05_ENABLED" | "GITHUB_SEATS06_ENABLED" | "GITHUB_SEATS07_ENABLED" | "AWS_ACCESS_KEY_ID" | "AWS_SECRET_ACCESS_KEY" | "GITHUB_TOKEN">> {}
}
